const pdf = require('html-pdf');

const options = {
  format: 'A4',
  "border": {
    "top": "0.5in", // default is 0, units: mm, cm, in, px
    "right": "0.3in",
    "bottom": "0.2in",
    "left": "0.3in"
  },
  footer: {
    contents: {
      default: '<div style="font-size: 6pt; text-align:center; color: gray; margin: auto">Generated by <strong>https://github.com/antonybudianto/node-firebase-resume</strong></div>'
    }
  }
};

function generatePdf(content) {
  return new Promise((resolve, reject) => {
    pdf.create(content, options)
    .toFile('./dist/cv.pdf', function(err, res) {
        if (err) return reject(err);
        resolve(res);
    });
  });
}

module.exports = {
  generatePdf: generatePdf
};
